export enum TagsEnum {
  Untagged = "UNTAGGED",
  BadRequest = "BAD_REQUEST",
  NotFound = "NOT_FOUND",
  InternalServerError = "INTERNAL_SERVER",
  Unauthorized = "UNAUTHORIZED",
  Forbidden = "FORBIDDEN",
  Conflict = "CONFLICT",
  TooManyRequests = "TOO_MANY_REQUESTS",
  UnprocessableEntity = "UNPROCESSABLE_ENTITY",
  LockedUser = "LOCKED_USER",
  DisabledUser = "DISABLED_USER",
  DbResourceNotFound = "DB_RESOURCE_NOT_FOUND",
  InvalidEntity = "INVALID_ENTITY",
  MailerError = "MAILER",
  Expired = "EXPIRED",
  CacheMiss = "CACHE_MISS_KEY",
  DBTransaction = "DB_TRANSACTION",
  RequiredRefreshToken = "REQUIRED_REFRESH_TOKEN",
}
